openapi: 3.0.3

info:
  title: Tickets API
  version: 1.0.0

paths:
  /tickets:

    get:
      summary: Obtener tickets

      operationId: findTickets

      responses:
        '200':
          description: Lista tickets

          content:
            application/json:
              schema:
                type: array

                items:
                  $ref: '#/components/schemas/TicketResponse'

    post:
      summary: Crear ticket

      operationId: createTicket

      requestBody:
        required: true

        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTicketRequest'

      responses:
        '201':
          description: Ticket creado

          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketResponse'

components:

  schemas:

    CreateTicketRequest:

      type: object

      required:
        - title
        - description
        - priority

      properties:
        id:
          type: number
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
            - IN_PROGRESS
            - REGISTERED
            - CLOSED
            - PENDING_CUSTOMER
            - RESOLVED
        priority:
          type: string
          enum:
            - LOW
            - MEDIUM
            - HIGH
            - CRITICAL

        sourceAreaReq:
          $ref: '#/components/schemas/areaReq'
        targetAreaReq:
          $ref: '#/components/schemas/areaReq'

        sourceGroupReq:
          $ref: '#/components/schemas/groupReq'
        targetGroupReq:
          $ref: '#/components/schemas/groupReq'

    areaReq:
      type: object
      properties:
        id:
          type: number
        nombre:
          type: string

    groupReq:
      type: object
      properties:
        id:
          type: number
        nombre:
          type: string

    requesterReq:
      $ref: '#/components/schemas/userReq'
    assignedToReq:
      $ref: '#/components/schemas/userReq'

    userReq:
      type: object
      properties:
        id:
          type: number
        nombre:
          type: string

    createdReq:
      type: string

    TicketResponse:

      type: object
      properties:
        id:
          type: number
        title:
          type: string
        status:
          type: string
        priority:
          type: string